### PR TITLE
Dethfest website v1.0

### PR DESCRIPTION
**Pull request by AkashaRojee**
Hello!

I built the HTML/CSS + JS capstone project. Please, find the details below and review the project.

## Video

[View video about project](https://www.loom.com/share/e495c1f4cad846d8b3512d27eb620c33)

---

Note about the delay: I modularised my HTML using Jekyll and also ran into linter issues because of the different directory structure. This has been solved now, though. I notified the Student Success Team about the situation and I was told to include the information in the PR.

---

## Design

The design is based on a conference website template. [View template here](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015).

We have been requested to personalise the content. So, I have customised it accordingly for a concert website. The concert is a Metal concert, hence the use of dark backgrounds.

### Note:

- Instead of speakers, there are bands. So, instead of speaker photos, there are band logos.

- The card elements are placed vertically because band logos are wide and won't be legible if placed as a small image on the side of the card.

## General structure of the website

- Flexbox is used for positioning
- Break down HTML into partials using Jekyll
- Make CSS reusable and dynamic throughout entire website using custom-built libraries and SCSS mixins
- JS is modularised using custom-built functions

## Things done

- Build pages for Home and About
- Use media queries to make website responsive in mobile (up to 768 px) and desktop (above 768 px) view
- Logo in header links to Home page
- "About" in header links to About page
- Mobile menu is available in mobile view and can be opened/closed
- "Program" and "Featured Bands" ("Featured Speakers") sections are populated dynamically
- 1 variable used to store information for all bands, and another for all programs

---
Thanks!

### CODE REVIEW

**Review by de-scholar — CHANGES_REQUESTED** [review]
Hi @AkashaRojee , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._
- [x] I suggest you add a way for navigating back to homepage while on about page in mobile screens
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 4 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AkashaRojee** [comment]
Hi @de-scholar,

Thanks for the feedback! This is actually a great suggestion.

I have now added a link to Home in mobile view.

For this purpose, I made visible the header logo, which already links to Home in desktop view. The menu button is thus now located on the right of the navigation bar.

Thanks!

**Review by smcommits — APPROVED** [review]
### Status: Approved 👍🏽 

Hi @AkashaRojee, 

## You have done a great job! Your project is complete. This PR is now approved. You can go ahead and merge the branch. Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by AkashaRojee** [comment]
Hi @smcommits,

Thanks!

**Pull request merged**
